/*
 * led.c
 *
 *  Created on: Nov 8, 2016
 *      Author: sahan
 */

#include "MKL25Z4.h"
void yellow()
{

	int i=0;
MCG_BASE_PTR->C1 = MCG_C1_IREFS_MASK | MCG_C1_IRCLKEN_MASK;
MCG_BASE_PTR->C2 = MCG_C2_IRCS_MASK; //Select fast internal clock
SIM_BASE_PTR->SCGC6 |= SIM_SCGC6_TPM2_MASK; //Enable TPM2 clock
SIM_BASE_PTR->SOPT2 |= SIM_SOPT2_TPMSRC(3);
TPM2_BASE_PTR->SC = TPM_SC_CMOD(1) | TPM_SC_PS(7);
TPM2_BASE_PTR->MOD = 16383;
SIM_BASE_PTR->SCGC5 |=SIM_SCGC5_PORTB_MASK;
PORTB_BASE_PTR->PCR[18] =PORTB_BASE_PTR->PCR[19]=PORT_PCR_MUX(3);
GPIOB_PDDR= 1<<18 | 1<<19;
TPM2_BASE_PTR->CONTROLS[0].CnSC = TPM_CnSC_MSB_MASK | TPM_CnSC_ELSA_MASK;
TPM2_BASE_PTR->CONTROLS[1].CnSC = TPM_CnSC_MSB_MASK | TPM_CnSC_ELSA_MASK;
TPM2_BASE_PTR->CONTROLS[0].CnV=TPM2_BASE_PTR->CONTROLS[1].CnV = TPM2_BASE_PTR->MOD;
}
void red()
{
MCG_BASE_PTR->C1 = MCG_C1_IREFS_MASK | MCG_C1_IRCLKEN_MASK;
MCG_BASE_PTR->C2 = MCG_C2_IRCS_MASK; //Select fast internal clock
SIM_BASE_PTR->SCGC6 |= SIM_SCGC6_TPM2_MASK; //Enable TPM2 clock
SIM_BASE_PTR->SOPT2 |= SIM_SOPT2_TPMSRC(3);
TPM2_BASE_PTR->SC = TPM_SC_CMOD(1) | TPM_SC_PS(7);
TPM2_BASE_PTR->MOD = 16383;
SIM_BASE_PTR->SCGC5 |=SIM_SCGC5_PORTB_MASK;
PORTB_BASE_PTR->PCR[18]=PORT_PCR_MUX(3);
GPIOB_PDDR= 1<<18;
TPM2_BASE_PTR->CONTROLS[0].CnSC = TPM_CnSC_MSB_MASK | TPM_CnSC_ELSA_MASK;
TPM2_BASE_PTR->CONTROLS[0].CnV= TPM2_BASE_PTR->MOD/8;
}
void Green()
{
	MCG_BASE_PTR->C1 = MCG_C1_IREFS_MASK | MCG_C1_IRCLKEN_MASK;
	MCG_BASE_PTR->C2 = MCG_C2_IRCS_MASK; //Select fast internal clock
	SIM_BASE_PTR->SCGC6 |= SIM_SCGC6_TPM2_MASK; //Enable TPM2 clock
	SIM_BASE_PTR->SOPT2 |= SIM_SOPT2_TPMSRC(3);
	TPM2_BASE_PTR->SC = TPM_SC_CMOD(1) | TPM_SC_PS(7);
	TPM2_BASE_PTR->MOD = 16383;
	SIM_BASE_PTR->SCGC5 |=SIM_SCGC5_PORTB_MASK;
	PORTB_BASE_PTR->PCR[19]=PORT_PCR_MUX(3);
	GPIOB_PDDR= 1<<19;
	TPM2_BASE_PTR->CONTROLS[1].CnSC = TPM_CnSC_MSB_MASK | TPM_CnSC_ELSA_MASK;
	TPM2_BASE_PTR->CONTROLS[1].CnV= TPM2_BASE_PTR->MOD/8;
}
void Blue()
{

	MCG_BASE_PTR->C1 = MCG_C1_IREFS_MASK | MCG_C1_IRCLKEN_MASK;
	MCG_BASE_PTR->C2 = MCG_C2_IRCS_MASK; //Select fast internal clock
	SIM_BASE_PTR->SCGC6 |= SIM_SCGC6_TPM0_MASK; //Enable TPM2 clock
	SIM_BASE_PTR->SOPT2 |= SIM_SOPT2_TPMSRC(3);
	TPM0_BASE_PTR->SC = TPM_SC_CMOD(1) | TPM_SC_PS(7);
	TPM0_BASE_PTR->MOD = 16383;
	SIM_BASE_PTR->SCGC5 |=SIM_SCGC5_PORTD_MASK;
	PORTD_BASE_PTR->PCR[1] =PORT_PCR_MUX(4);
	GPIOD_PDDR= 1<<1;
	TPM0_BASE_PTR->CONTROLS[1].CnSC=TPM_CnSC_MSB_MASK|TPM_CnSC_ELSA_MASK;
	TPM0_BASE_PTR->CONTROLS[1].CnV=TPM0_BASE_PTR->MOD/8;
}
void voilet()
{
	MCG_BASE_PTR->C1 = MCG_C1_IREFS_MASK | MCG_C1_IRCLKEN_MASK;
	MCG_BASE_PTR->C2 = MCG_C2_IRCS_MASK; //Select fast internal clock
	SIM_BASE_PTR->SCGC6 |= SIM_SCGC6_TPM0_MASK; //Enable TPM2 clock
	SIM_BASE_PTR->SOPT2 |= SIM_SOPT2_TPMSRC(3);
	SIM_BASE_PTR->SCGC5 |=SIM_SCGC5_PORTB_MASK;
	PORTB_BASE_PTR->PCR[18] =PORT_PCR_MUX(3);
	GPIOB_PDDR= 1<<18;
	SIM_BASE_PTR->SCGC5 |=SIM_SCGC5_PORTD_MASK;
	PORTD_BASE_PTR->PCR[1] =PORT_PCR_MUX(4);
	GPIOD_PDDR= 1<<1;
	TPM2_BASE_PTR->CONTROLS[0].CnSC=TPM_CnSC_MSB_MASK|TPM_CnSC_ELSA_MASK;
	TPM2_BASE_PTR->CONTROLS[0].CnV=TPM2_BASE_PTR->MOD/8;
	TPM0_BASE_PTR->CONTROLS[1].CnSC=TPM_CnSC_MSB_MASK|TPM_CnSC_ELSA_MASK;
	TPM0_BASE_PTR->CONTROLS[1].CnV=TPM0_BASE_PTR->MOD/8;
}
void cyan()
{
Blue();
Green();
}

void off()
{
	Blue();
	Green();
	red();
}
void intensity(int inten)
{
	int MOD=32000;
if(inten==0)
{
	TPM2_BASE_PTR->MOD=320*inten;
	TPM2_BASE_PTR->CONTROLS[0].CnSC=TPM0_BASE_PTR->CONTROLS[1].CnV=TPM_CnSC_MSB_MASK|TPM_CnSC_ELSA_MASK;
	TPM2_BASE_PTR->CONTROLS[0].CnV=TPM2_BASE_PTR->MOD/2;
	TPM0_BASE_PTR->CONTROLS[1].CnV=TPM0_BASE_PTR->MOD/2;
}
else
{
	inten=inten-10;
	TPM2_BASE_PTR->MOD=320*inten;

	TPM0_BASE_PTR->CONTROLS[1].CnV=TPM0_BASE_PTR->MOD;
}
}




